#!/bin/bash

# Street Tycoon App Icon Creation Guide
# This creates a professional money/tycoon themed app icon

echo "🏴‍☠️ Creating Street Tycoon App Icon..."
echo ""
echo "Icon Design Specifications:"
echo "📐 Size: 1024x1024 pixels (high resolution)"
echo "🎨 Background: Black to dark gradient (#000000 → #1a1a1a)"
echo "✨ Primary: Gold (#FFD700)"
echo "🔸 Accent: Orange-gold (#FF8C00)"
echo "💰 Symbol: Large dollar sign ($) with crown"
echo "🎯 Style: Circular, professional, high contrast"
echo ""
echo "Icon Elements:"
echo "1. ⚫ Black circular background with subtle gradient"
echo "2. 💰 Large golden dollar sign ($) in center (60% of icon)"
echo "3. 👑 Small crown above dollar sign for 'tycoon' theme"
echo "4. ✨ Gold ring border for premium feel"
echo "5. 🌟 Subtle glow/shadow effect"
echo ""
echo "Quick Creation Options:"
echo ""
echo "🌐 Online Tools (Recommended):"
echo "   • Canva.com - Search 'money app icon' templates"
echo "   • AppIcon.co - AI-powered icon generator"
echo "   • IconKitchen.com - Material Design icons"
echo "   • DesignEvo.com - Professional icon maker"
echo ""
echo "🎨 Design Software:"
echo "   • GIMP (Free) - Use text tool for $ symbol"
echo "   • Adobe Illustrator - Vector icons (best quality)"
echo "   • Figma - Free, web-based design"
echo ""
echo "📱 Android Icon Requirements:"
echo "   • 1024x1024 - Google Play Store"
echo "   • 192x192 - xxxhdpi"
echo "   • 144x144 - xxhdpi"
echo "   • 96x96 - xhdpi"
echo "   • 72x72 - hdpi"
echo "   • 48x48 - mdpi"
echo ""
echo "💡 Pro Tips:"
echo "   • Use bold, simple shapes for small sizes"
echo "   • High contrast (gold on black works great)"
echo "   • Test icon at 48x48 to ensure readability"
echo "   • Avoid fine details that disappear when small"
echo ""
echo "🎯 Quick Template:"
echo "   1. Create 1024x1024 black circle"
echo "   2. Add gold border (20px thick)"
echo "   3. Place large gold $ symbol in center"
echo "   4. Add small crown icon above $"
echo "   5. Export as PNG with transparency"
echo ""
echo "Icon created! Place the 1024x1024 PNG as:"
echo "📂 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"
